### ISSUE TITLE
Geocoder improvements

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#1262]
For the most part, these are just my ideas/suggestions left over from #1157  If you have other ideas, or feel that any of these don't belong, let me know.
- [x] Add event for flight completion
- [x] Clear Geocoder when home button is pressed
- [x] Add button to clear text field rather than making the user hit backspace a bunch (this is a bigger pain on mobile)
- [ ] Detect touch support and remove hover from style sheet to fix focus issues on mobile.
- [x] ~~If Bing supports it, auto-completion would be great.~~
- [x] The ability to specify a custom geocoder (with custom autocomplete suggestions).
- [x] Possible have multiple geocoders each offering their own suggestions to allow for domain specific searching.
- [ ] Time based geocoding so that you can fly to an area at a particular time. (may be tricky to do)
- [x] Bug with lon/lat positions: #4713

**Comment by pjcozzi** [comment]
> enter a longitude, latitude in degrees and fly to it.

I needed this for testing, it is in the [geocoder-fly](https://github.com/AnalyticalGraphicsInc/cesium/compare/geocoder-fly) branch.

**Comment by pjcozzi** [comment]
This was requested on the forum:

* [ ] [Custom queries](https://groups.google.com/forum/#!topic/cesium-dev/Pr2vv87299I)

**Comment by hpinkos** [comment]
"It is not recommended to use the geocoding service to power an auto complete function" [forum post](https://social.msdn.microsoft.com/Forums/en-US/f570ddc1-2d5f-40c6-ba66-7a5ccc8f4138/bing-maps-location-api-for-autocomplete-addresses-no-apartments?forum=bingmapsservices)

The bing maps "locations" REST API doesn't have any way of asking for the top results that start with whatever you are typing, so it currently cannot be used for autocomplete.

**Comment by hpinkos** [comment]
Pretty much everything in this issue is addressed.  I'm going to close this and open a new issue for the 1 mobile fix we still have to make.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/Pr2vv87299I

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/1262 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:
