### ISSUE TITLE
Vector Data on Terrain

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2172]
Vector data: polygons, polylines, and billboards/labels.

For now just a placeholder to gather reading material.  More to come.
- [Usability Oriented Visualization Techniques for 3D Navigation Map Display](http://mediatum.ub.tum.de/doc/1195222/1195222.pdf).  2014.
- [An improved algorithm for vector data rendering in virtual terrain visualization](http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=6626137&url=http%3A%2F%2Fieeexplore.ieee.org%2Fxpls%2Fabs_all.jsp%3Farnumber%3D6626137).  2013.
- [A screen-space approach to rendering polylines on terrain](http://blogs.agi.com/agi/2011/04/25/a-screen-space-approach-to-rendering-polylines-on-terrain/).  2011.
- [Visualization methods of vector data on a Digital Earth System](http://ieeexplore.ieee.org/xpl/login.jsp?tp=&arnumber=5567902&url=http%3A%2F%2Fieeexplore.ieee.org%2Fiel5%2F5559273%2F5567473%2F05567902.pdf%3Farnumber%3D5567902).  2010.
- [RENDERING 3D VECTOR DATA USING THE THEORY OF STENCIL SHADOW VOLUMES](http://www.isprs.org/proceedings/XXXVII/congress/2_pdf/5_WG-II-5/06.pdf).  2008.
- [Efficient and accurate rendering of vector data on virtual landscapes](http://cg.cs.uni-bonn.de/en/publications/paper-details/schneider-2007-efficient/).  2007.

**Comment by vmora** [comment]
Last link seems broken, here is the paper http://wscg.zcu.cz/WSCG2007/Papers_2007/journal/B17-full.pdf

And a review here http://vterrain.org/Misc/draping.html

**Comment by pjcozzi** [comment]
@bagnell can you evaluate volume decals as an approach for polygons/polylines on terrain?  Think about performance and precision.

   * [Volume roads](http://www.humus.name/index.php?page=3D&ID=84)
   * [Volume decals](http://www.humus.name/index.php?page=3D&ID=83)

I don't know how to make it fast for polygons; it needs either a convex decomposition (not necessarily as fine-grained as triangulation) or a per-pixel point-in-polygon test (which, if done with a 2D texture of the polygon would have all the drawbacks of just rasterizing a texture as an image layer).

**Comment by pjcozzi** [comment]
@bagnell here are some notes for the shadow volume approach:

* [ ] Remember not to use the bounding sphere for the polygon itself since the real polygon is where the volume intersects terrain.  The most conservative thing to do is to use the bounding sphere of the volume, but I think we can do better.
* [ ] To save fillrate, instead of using the max altitude to extrude up, we should add a function to the terrain provider to return the max (and perhaps min) height of an extent based on the loaded terrain (perhaps with a callback for refinement?).  To start, this could be based on the bounding sphere of each (or max height when it is lower), but we could make this much better with a quantized-mesh extension that keeps min/max per node.  This could also be a web service.

**Comment by pjcozzi** [comment]
Notes from our discussion on **billboards/labels**:

* [ ] Depth test origin in vertex shader using terrain depth buffer.  This will require VTF, which is 97% supported ([MAX_VERTEX_TEXTURE_IMAGE_UNITS](http://webglstats.com/)).
* [ ] Query height from terrain provider.  Have callback for when it refines.  Entity layer will update the billboards height.
* [ ] Longer-term, we might need to ability to only show the closest/most-important `x` number of labels and not depth test them.  This allows us to see labels through terrain, buildings, etc.

**Comment by pjcozzi** [comment]
Also, I expect screen-space approaches (shadow volume, decal, etc.) to be much better for runtime editing than texture and sub-sampling approaches (sub-sampling may be OK, but I expect re-rasterizing the texture, especially if we made a sparse quadtree out of it, would be painfully slow).

**Comment by pjcozzi** [comment]
> Query height from terrain provider.

I'm not sure what the implementation looks like now, but we can do much better than brute force look at each triangle.  We can assume the triangle last used will be used next, and also use adjacency information (pre-compute once on the client I guess, or as a quantized-mesh extension) or a quad-tree arrangement inside the tile to find the right triangle.

> Have callback for when it refines. Entity layer will update the billboards height.

This could be done on a web worker, e.g., each time we get a new tile, a web worker looks at all the subscribed positions to queue up callbacks (or events).  This could be the same worker that processes the tile for visualization or a separate one to decrease the latency for terrain visualization at the cost of delaying the vector data update.

**Comment by pjcozzi** [comment]
@bagnell perhaps we do polylines last.  We can evaluate shadow volumes for them using the corridor geometry and sub-sampling using the infrastructure we'll build for billboards/labels.  Chapter 3 of [Usability Oriented Visualization Techniques for 3D Navigation Map Display](http://mediatum.ub.tum.de/doc/1195222/1195222.pdf) is a nice comparison, but their sub-sampling does exact line-segment/triangle intersections - and still does not get adequate visual quality for high-resolution terrain.

**Comment by kring** [comment]
> To start, this could be based on the bounding sphere of each (or max height when it is lower), but we could make this much better with a quantized-mesh extension that keeps min/max per node.

Not sure what you mean here.  Quantized mesh tiles already know the min and max height of any point within the tile.  Is that what you're referring to, or do you need something else?  Actually, heightmap tiles do, too, it's just computed at load time.

**Comment by pjcozzi** [comment]
> do you need something else?

No.  That will do it.  I clearly didn't look at the format.

**Comment by pjcozzi** [comment]
@bagnell I had more ideas about point-in-volume.

We already discussed:
* If not already in it: `bounding sphere` -> `extruded convex hull` -> `exact test`
* If already in it: `inscribed sphere` -> `inscribed convex hull` -> `exact test` (actually probably check `bounding sphere` and `extruded convex hull` before the `exact test`)
* Later: consider BVH to avoid O(n) over all polygons.

Here's a few more ideas:
* Probably need a heuristic to see if the convex hull is worth it, e.g., if the polygon is already convex or can be broken into a few convex regions.
* I think we should start by coding the generic point (or near plane?) in extruded volume, but I suspect we will also want an optimized version for our unique case:
   * We don't need to check the bottom cap under terrain
   * In general, we'll need to check the top cap, testing each triangle would be slow, but I think we can get away with just checking the camera's height.  However, I expect there will be an issue because that assumes an infinite tessellate of the top cap, so we may need to check a conservative height, and then check the triangles (unless the camera is above a max height).

**Comment by pjcozzi** [comment]
Recent paper:

* [Practical line rasterization for multi-resolution textures](http://www.crs4.it/vic/data/papers/stag2014-line_rasterization.pdf), 2014

**Comment by pjcozzi** [comment]
Feedback on polygons on terrain (in progress) is in #2618.

**Comment by bagnell** [comment]
- [ ] Add dynamic minimum height. (Needs changes to supported geometries)
- [ ] Query terrain for tighter maximum height.
- [ ] Add option to geometries for creating different bounding volumes.
- [ ] Batch by color?
- [ ] Tighter OBB? Maybe compute from [triangles](http://gamma.cs.unc.edu/users/gottschalk/main.pdf)

**Comment by likangning93** [comment]
> Usability Oriented Visualization Techniques for 3D Navigation Map Display. 2014.

That thing is like a *Hitchiker's Guide* or something waoww

**Comment by pjcozzi** [comment]
I only read the abstraction, but this could be interesting:

> **Deferred vector map visualization**
>
> Interactive rendering of large scale vector maps is a key challenge for high-quality geographic visualization software systems. In this paper we present a novel approach for the visualization of large scale vector maps over detailed height-field terrains. Our method uses a deferred line shading approach to render large scale vector maps directly in a screen-space shading stage over a terrain visualization. The fact that there is no traditional geometric polygonal rendering involved allows our algorithm to outperform conventional vector map rendering algorithms for geographic information systems. Our flexible clustered deferred line rendering approach allows a user to interactively customize and apply advanced vector styling methods, as well as the integration into a vector map level-of-detail system.
>
> https://dl.acm.org/citation.cfm?doid=3002151.3002157


@likangning93 have a read and let us know what you think.

**Comment by Thoenu** [comment]
hi all, you might want to consider our journal article which contains some more perfomance analysis. 

http://onlinelibrary.wiley.com/doi/10.1111/cgf.13294/abstract

**Comment by hpinkos** [comment]
Thanks for sharing @Thoenu!

**Comment by likangning93** [comment]
> Deferred vector map visualization
> https://dl.acm.org/citation.cfm?doid=3002151.3002157

This approach is amazing and terrifying. The crux is that instead of rendering "lines" as geometry, they do a full-screen post process pass that checks each terrain fragment in the current view to see how close it is to a line segment, with all the line segments stored in textures using a uniform grid of BVHes.

Concerns about precision issues aside, is it finally time for me to write a GPU BVH traversal? Is it finally my time?!

**Comment by likangning93** [comment]
> A screen-space approach to rendering polylines on terrain

[Via wayback machine](https://web.archive.org/web/20160427235210/http://blogs.agi.com/agi/wp-content/uploads/2011/04/PolylinesOnTerrainSupplement.pdf)

One beef I have with this technique is the requirement to render both a wall and a shadow volume, which seems more expensive for us because WebGL. However, combining this with ideas leveraging the batch table for fragment culling in https://github.com/AnalyticalGraphicsInc/cesium/pull/6393, I wonder if we could:
* render a thin volume for each line segment, carrying a batch ID mapping to start/end positions and a quaternion or something describing a local coordinate system with the XY plane tangent to the ellipsoid
* for each fragment, look up globe depth and compute a world position. Squash that world position and start/end positions into the XY plane of the local coordinate system and check for colinearity with start/end

We'd have to disable early Z I think, but maybe that's not such a large price to pay to cut this down to a single pass.

**Comment by likangning93** [comment]
The colinearity approach also gives us data that could be vital for doing style stuff.

**Comment by likangning93** [comment]
Question: what's the extent of material support that we want here? There's an awesome development [Polyline Color sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=7VVRb9owEP4rJ14aVuYALS+UVqsonSZtatVV1aQxTW5ygDXHtmwHyir++y5OwghUe5hUaQ/jBfvuvu/uvjsrcQxji9wj+AXCUuAKLZuqJbfVBc5B4QrG6ESesYdgi46ScB1r5blQaI/aZyXGJaiQIBVRuJJrquIYJk88MxKhN4Qry1fAwWi5loSHlfALMJTM4TxD5SHRUltXchrthBdaOeL9+q1KVAbsWgT9z7SFSJC1ewYCRtDrn8HxsWjD81QB/bZUzORuEVVNjbn1dOLqhM2szq5wbhFd9LbXP2VdOIbBG9GB0y7rtos2C54ye5OkMAX8HVepzqJnLs2CwxB6rLsJyE2Q4ZpqPGhVqHkHXG6MXIdBVO1pU1Qb5AlYroBby9egZ3VI0TLyZFHz0fCC6sxYkVGzS3SMp2m0M8Tb2hNVssxRZ+jt+oNyniuaLVW9E/9+z13DdqFNxG012Bq5i2jMgWDbc6cZsxIpLcUQBqy751kizeuJdMy4p4C9nGEQl8Ygt0Wx7GFydz/58v365u7T5f0eU6XhcLtvtWPTLs+bdoXgW8KXO93LGhG+HHpj9ft/WP2yq20lB1vf3PhX3PSTwT++6aVSDOBSOk3sviAKqDLyFu1DKWbF6jV4m+P/p/H3T+NF72+hh0Hg13g/rU5r5Pxa4kVJ9E5kRlsPuZURY7FHelj0+XLxY578QM8S5wrYKK5Bo1QsQaTn09beR2vagkRy58gzy6X8LH7itHUxiim+AZOap7S1N6St5OsiZNG7+FgaGWOjmK6HKK+1fOR2h/EX) and I'm... not sure how to do that when we're working in fragment space.

**Comment by pjcozzi** [comment]
For style, start with color and line width.  Then dash.  Then textures.

**Comment by likangning93** [comment]
So the "single pass shadow volume for lines" trick above probably has the same problems as any other shadow volume algorithm for polylines on terrain, namely, difficulty keeping constant screen space width:
* when drawn perpendicular to the gradient of a steep slope and viewed edge-on
* when viewed at horizon-facing angles on flat ground

But since it's single-pass and doesn't require any special render state it can possibly still share a draw call with @pjcozzi's wall algorithm, which a conventional shadow volume can't do. So that's still kind of promising.

**Comment by likangning93** [comment]
> "single pass shadow volume for lines" trick

I think this technique has enough promise that we can start assembling a gameplan. Here's a couple shots of my prototype at various view distances, we should be able to simulate "constant screen space width" reasonably well:

![near](https://user-images.githubusercontent.com/5395255/39945098-2d7e07fe-5537-11e8-8364-ea6eb01287dc.JPG) | ![far](https://user-images.githubusercontent.com/5395255/39945103-33258740-5537-11e8-89d6-5d23704151d5.JPG) | 
![wherever you are](https://user-images.githubusercontent.com/5395255/39945114-3b98f6be-5537-11e8-8ab4-6e24af581e86.JPG)
:-------------------------:|:-------------------------:|:-----------:
near  |  far | ~~wherever you are~~

I think through the `Primitive` API this is going to look something like a custom `Geometry` type (to be used via a method that builds arrays of `GeometryInstances`) and a custom Primitive type that will really just be a lightweight wrapper around `Primitive` but might have to tangle a bit with `GroundPrimitive` for terrain info.

How should this integrate into the Entity API though? Just something like an `onTerrain` flag that you can add to polyline entities? I'm reasonably sure that this is going to need its own spaghetti of updaters and batchers under the hood due to the custom `Primitive`.

It might also be wisest to start off with material support limited to, say, simple colors, but I'll try to have a more concrete idea of how difficult full material support will be soon.

**Comment by hpinkos** [comment]
@likangning93 at the entity level, polylines already have a `followSurface` option that defaults to true.  I imagine we would use this as the new default and use `PolylineGeometry` when `followSurface: false` or if it's using a material that's unsupported

**Comment by likangning93** [comment]
> when drawn perpendicular to the gradient of a steep slope and viewed wall-on

Fun idea: we might already have slopes available somewhere because of materials on terrain, and if not we can also compute per-fragment terrain slopes like we do for materials on ground primitives. Wonder if this would be useful for reducing smearing on slopes.

Something to experiment with a little later.

**Comment by mramato** [comment]
@hpinkos can confirm, but I believe we compute slopes in the material shader and it requires vertexnormals be part of the the terrain data (so they are technically not always available).  I'm fine with requiring them, but we may need to either throw an error or provide a fallback (which can be not clamping to terrain).

**Comment by hpinkos** [comment]
> I believe we compute slopes in the material shader and it requires vertexnormals be part of the the terrain data (so they are technically not always available)

Yep, see https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Globe%20Materials.html

**Comment by pjcozzi** [comment]
@likangning93 can we close this?

**Comment by likangning93** [comment]
@pjcozzi :+1: from me
