### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2594]
* [ ] Globe depth debug view
* [ ] Experimental shadow pass for one light like `Scene.pick` with a debug view
* [ ] Production shadow pass
   * One `updatePrimitives` call
   * If the light and its area of influence are outside of the view frustum, skip its shadow pass
* [ ] Experimental shadows on terrain
* [ ] Architecture for adding shadow-casting lights, and flagging shadow-casting and shadow-receiving objects, e.g., polylines and billboards do not always need to cast shadows.
* [ ] Figure out multifrustum / Cascaded Shadow Maps

**Later**

* [ ] Color pass and shadow passes should not trash the terrain/imagery cache
* [ ] Shadow pass does not need to load imagery
* [ ] Generate custom shaders for shadow pass that only set depth/discard, not shade
* [ ] Shadows on models and other primitives
* [ ] PCF soft shadows

**Reading**

* [Data Driven Renderer Details](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Data-Driven-Renderer-Details)
* [Shadow mapping on large terrain](http://organicvectory.com/index.php?option=com_content&view=article&id=54:shadow-mapping-on-large-terrain&catid=1:articles&Itemid=61)

It will only be a small jump from here to add a cube map pass for reflection/refraction, AO, and IBL.

CC @fstoner

**Comment by simonthum** [comment]
We are interested in shadows in cesium and the approach outlined looks like it fits the bill. If I may ask, is there any current development, and is the state of affairs presented here up to date?

**Comment by pjcozzi** [comment]
This is current.  See https://github.com/fstoner/cesium/tree/depth-map

**Comment by simonthum** [comment]
Thanks a lot!

**Comment by pjcozzi** [comment]
Looks like a nice resource: http://learnopengl.com/#!Advanced-Lighting/Shadows/Shadow-Mapping

**Comment by pjcozzi** [comment]
_Could_ be related: [Practical Shading of Height Fields and Meshes using Spherical Harmonic Exponentiation](http://www.iro.umontreal.ca/~derek/publication.html?id=51)

**Comment by pjcozzi** [comment]
> Support multiple shadow maps at once.

Is this done, excluding multiple lights, of course?

**Comment by kjartab** [comment]
@pjcozzi - the item called "Cast shadows for terrain tiles that are out of view: on the shadows-globe branch." - has any work been done towards it? We using shadows in cesium for buildings and terrain - which works great as long as you point the camera in the sun's direction - but when facing away the shadows dissapear of course. Do you have any idea about how much work this would require to implement? And possibly which part of the source code one would start looking at?

**Comment by pjcozzi** [comment]
> @pjcozzi - the item called "Cast shadows for terrain tiles that are out of view: on the shadows-globe branch."

Hi @kjartab - I don't believe anyone has made progress towards this.  It may require a fair amount of work deep in the rendering engine and 3D Tiles LOD selection as the tiles in the shadow frustum need to be requested and this should not interfere with the tile caching for the main rendering pass.  If you are familiar with the rendering engine and shadow algorithms, we could probably find someone to point you in the right direction but just a heads up that it might be a large effort. 😄
