### ISSUE TITLE
Billboard and labels roadmap

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#2685]
* [ ] Optimize ray/terrain intersection when getting height.  At least add a 2x2 or 4x4 grid, if not an octree/quadtree that is a few levels deep.  That will probably take a day and produce a 10x gain.  Also consider temporal coherence, adjacency info, and simplifying the math for the case when the ray is along (well opposite) the ellipsoid normal.
* [ ] Billboard ground shadows to give a better sense of placement.  These could be faked like the Milktruck shadows.  Perhaps have a sparse texture with the longitude/latitudes and then do a simple blurred black circle at each point in the terrain pass.
* [ ] Multipass with transform-feedback or occlusion queries (CC #797), e.g., we could determine if a billboard is `x%` visible in one pass then cull it in the next pass to be more precise than VTP.

**Comment by emackey** [comment]
See also some ideas re-thinking the way points/billboards/labels could be separated from the 3D scene, in https://github.com/AnalyticalGraphicsInc/cesium/issues/2694#issuecomment-339086615
