### ISSUE TITLE
Shapefile Roadmap 

### ISSUE THREAD

**Issue by andre-nunes** [AnalyticalGraphicsInc/cesium#2750]
#### References

[ESRI Shapefile whitepaper](http://www.esri.com/library/whitepapers/pdfs/shapefile.pdf)

[Wikipedia page](http://en.wikipedia.org/wiki/Shapefile)

[Shapefiles on OpenStreetMapWiki](http://wiki.openstreetmap.org/wiki/Shapefiles)
#### Somewhat related javascript Implementations

https://github.com/wavded/js-shapefile-to-geojson
https://github.com/RandomEtc/shapefile-js/
https://github.com/mbostock/shapefile
#### Roadmap
- [ ] Evaluate potential third-party shapefile readers
- [ ] ShapefileDataSource
  - [ ] load/parse main file .shp
  - [ ] load/parse index file .shx
  - [ ] load/parse dbase file .dff
- [ ] NULL shapes
- [ ] Point, PointM, PointZ
- [ ] MultiPoint, MultiPointM, MultiPointZ
- [ ] Polyline, PolylineM, PolylineZ
- [ ] Polygon, PolygonM, PolygonZ

_(Z and M variants in the same checkbox item, yes or no?)_
- [ ] Multipatch
  - [ ] Triangle Strip
  - [ ] Triangle Fan
  - [ ] Outer Ring
  - [ ] Inner Ring
  - [ ] First Ring
  - [ ] Ring
- [ ] Achieve good test coverage
- [ ] Write/improve documentation
- [ ] Write Tutorial/Blog post about usage in Cesium

---

**Comment by GatorScott** [comment]
There's a convention, established by Esri's Tracking Analyst, which defines support for temporal data within a shapefile.  More information can be found [here](http://resources.arcgis.com/en/help/main/10.1/index.html#/Simple_and_complex_temporal_events/006300000008000000/).

**Comment by mramato** [comment]
Thanks @GatorScott, I somehow never heard of that capability before.  We'll definitely want to support it.

**Comment by pjcozzi** [comment]
@mramato what do you suggest here?  Close as OBE given future conversion to 3D Tiles and maybe CZML in some cases.

**Comment by mramato** [comment]
I think shapefiles will map nicely to what we have planned for vector tiles, so we're much better off spending our time there rather than trying to have direct shapefile support via entities.

**Comment by robmilton** [comment]
Just wondering where Cesium stands with support for shapefiles?

**Comment by hpinkos** [comment]
Hi @robmilton, we don't have plans to support shapefiles directly in CesiumJS at this time.  Instead, we're planning to offer shapefile to 3D tiles converter.  Alternatively, there are a number of shapefile tp geojson converters out there you can use.  Cesium support GeoJSON.
