### ISSUE TITLE
GPX Roadmap 

### ISSUE THREAD

**Issue by andre-nunes** [AnalyticalGraphicsInc/cesium#2751]
#### References

[Schema Documentation](http://www.topografix.com/gpx/1/1/)

[GPX on OpenStreetMap's Wiki](http://wiki.openstreetmap.org/wiki/GPX)

[GPX on Wikipedia](http://en.wikipedia.org/wiki/GPS_Exchange_Format)

[Good overview of the format](http://www.rigacci.org/wiki/doku.php/tecnica/gps_cartografia_gis/gpx)

#### Somewhat related javascript Implementations
https://github.com/mpetazzoni/leaflet-gpx
http://openlayers.org/en/master/examples/gpx.html
http://dev.openlayers.org/releases/OpenLayers-2.7/doc/apidocs/files/OpenLayers/Format/GPX-js.html
https://code.google.com/p/gpxviewer/
https://www.npmjs.com/package/gpx-parse

#### Roadmap

- [ ] GpxDataSource
  - [ ] load/parse .gpx
- [ ] Point
  - [ ] pt
  - [ ] ptseg
- [ ] Waypoint
- [ ] Track
  - [ ] trk 
  - [ ] trkseg (Track Segment)
  - [ ] trkpt (Track Point)
- [ ] Route
- [ ] bounds (Two lat/lon pairs defining the extent of an element.)
- [ ] Achieve good test coverage
- [ ] Write/improve documentation
- [ ] Write Tutorial/Blog post about usage in Cesium

**Comment by andre-nunes** [comment]
PR with initial support here: https://github.com/AnalyticalGraphicsInc/cesium/pull/2939

**Comment by OmarShehata** [comment]
GPX supported requested again on the forum: https://community.cesium.com/t/problem-rendering-kml-file-with-3d-terrain/9307. 

The latest on this is that there is a branch [`gpx`](https://github.com/AnalyticalGraphicsInc/cesium/tree/gpx) that's almost complete. Contributions welcome!
