### ISSUE TITLE
Renderer roadmap

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#3001]
- [ ] Refactor command execution. For example use `computeEngine.execute(command)` directly.
- [ ] Pass just `frameState` to update functions. Place `context` and `commandList` inside `frameState`.
- [ ] Separate command lists to avoid sorting based on pass type later.

**Comment by pjcozzi** [comment]
>  Refactor command execution. For example use computeEngine.execute(command) directly.

Looks OK for us to have `context.executeDrawCommand`, `context.executeClearCommand`, and `ComputeEngine.execute`.

**Comment by pjcozzi** [comment]
> 1. Separate command lists to avoid sorting based on pass type later.
> 2. Pass just frameState to update functions. Place context and commandList inside frameState.

I think we need to do (2) before doing (1), right?  Perhaps just hold on these for now.

**Comment by bagnell** [comment]
Derived command shaders are cached in the ShaderCache so they will be properly released when the original shader is. The same method of caching can be used for the derived render states.

**Comment by ggetz** [comment]
While this issue has useful context, I'm not sure anything here is immediately actionable without further planning. Closing for now.
