### ISSUE TITLE
3D Tiles Roadmap

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3241]
New to 3D Tiles?  See [Introducing 3D Tiles](https://cesiumjs.org/2015/08/10/Introducing-3D-Tiles/).

This work is in the [3d-tiles](https://github.com/AnalyticalGraphicsInc/cesium/compare/3d-tiles) branch.

In pseudo-priority order within each section:

* [ ] Tests and cleanup. #3177
* [ ] Review outstanding pull requests. #3237, #3080, #3076
* **Cesium internals** (not specific to 3D Tiles)
   * [ ] Request scheduler
   * [ ] Job scheduler, #2655
* **3D Tiles spec and Cesium implementation**
   * [ ] `refine` update. https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/7
   * [ ] Heterogeneous bounding volumes. https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/10
   * [ ] Vector tile format. https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/25
   * [ ] Declarative styling. https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/2
   * [ ] Terrain tile format. Will the initial Cesium implementation support overlaying separate imagery layers?
   * [ ] [Finalize tiles.json](https://github.com/AnalyticalGraphicsInc/3d-tiles#will-tilesjson-be-part-of-the-final-3d-tiles-spec).
   * [ ] Refinement parameters. https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/15
   * [ ] Finish/optimize i3dm tile format. https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/33
   * [ ] Finish point clouds tile format. https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/22
   * [ ] Increase bounding volume by pixel size.  See `Cesium3DTile` constructor.
   * [ ] Other small issues in the [3d-tiles](https://github.com/AnalyticalGraphicsInc/3d-tiles/issues) repo.
* **Cesium 3D Tiles implementation**
   * [ ] Is the load order correct?  For example, the buildings on the right should load sooner: http://cesiumjs.org/WashingtonDC/
   * [ ] Does culling with `content.box` still work? For example, the root tile for Canary Wharf is always rendered when just the tile's box is visible (even it the content box is not).
   * [ ] Cache management and replacement.
   * [ ] Add fog.
   * [ ] Support 2D and Columbus view?  This implies glTF support as well.
* **glTF** (and, therefore, b3dm)
   * [ ] Implement [WEB3D_quantized_attributes](https://github.com/KhronosGroup/glTF/blob/master/extensions/Vendor/WEB3D_quantized_attributes/README.md).
   * [ ] Finish spec and implementation for [mesh_compression_open3dgc](https://github.com/KhronosGroup/glTF/issues/398).
* **Cleanup**
   * [ ] Turn off opaque textures for picking pass, e.g., in Miami for rollover picking.
   * [ ] Stick with the `Cesium3DTile` prefix for names?
   * [ ] Review all `TODO` and `PERFORMANCE_IDEA` comments.
   * [ ] Move `DistanceDisplayCondition` and glTF changes to another branch?
* **Doc**
   * [ ] Reference doc.  Replace all `DOC_TBA`.
   * Tutorials
      * [ ] Using the flexibility of 3D Tiles for different scenarios, e.g., additive vs. replacement refinement, composite tiles vs. separate tilesets, etc.
      * [ ] Using the Cesium API to load 3D Tiles and interact with individual models.
      * [ ] Declarative styling.
   * [ ] Example tilesets beyond what is in the tests.
* [ ] Make `PointGeometry` and `PointAppearance` public. #3203

**Later**

* [ ] Texture LOD for b3dm
* [ ] Labels on buildings
* [ ] AO/IBL for 3D buildings
* [ ] Occlusion culling

**Comment by e-andersson** [comment]
Does "Cache management and replacement" include handling of which Cesium3DTilesets will be loaded or is it aimed at the lower-level tile handling? We're quite interested in tileset loading/unloading since we'll potentially have a large number of tilesets available to the viewer, causing a lot of initial tiles.json loading and repeating iteration over primitives.

**Comment by pjcozzi** [comment]
> Does "Cache management and replacement" include handling of which Cesium3DTilesets will be loaded or is it aimed at the lower-level tile handling?

It means lower-level tile handling, but thanks for reminding me about which `Cesium3DTileset` to load.  I added that to the roadmap. :)

If you are interested in working on either, I'm happy to discuss in more detail.

**Comment by pjcozzi** [comment]
> Stick with the Cesium3DTile prefix for names?

After doing a bunch of reference doc, I don't have a strong preference, but I am find with this, e.g.,
```
new Cesium.Cesium3DTileset
```
Compared to
```
new Cesium.Tileset3D
```
```
new Cesium.Tiles3D
```
```
new Cesium.ThreeDTileset
```
`Cesium.Tileset3D` would also be OK.  @lilleyse what do you think?

**Comment by pjcozzi** [comment]
@tomped I added a section above for you for when you start on 3D Tiles.

**Comment by TomPed** [comment]
> Rename Cesium3DTile#readyPromise to Cesium3DTile#contentReadyPromise

@pjcozzi does this mean the field `readyPromise` in the file `Cesium3DTile.js`?

**Comment by pjcozzi** [comment]
@TomPed yes.

**Comment by TomPed** [comment]
> Likewise, replace isReplacementRefinable and isContentUnloaded with readonly properties. Complete doc.

@pjcozzi I can't seem to find `isReplacementRefinable` in the project.

**Comment by lilleyse** [comment]
Ah, don't worry about that we removed that. I'll update the task.

**Comment by TomPed** [comment]
> *3DTileContentProvider*

Should this be `Cesium3DTileContentProvider`?

**Comment by lilleyse** [comment]
Yeah. The asterisks are just saying all things named like that.

**Comment by TomPed** [comment]
Oh gotcha, so I'll change anything with 3DTileContentProvider is to be changed to `3DTileContent`.

**Comment by lilleyse** [comment]
Yup

**Comment by lilleyse** [comment]
> Other than the tests, is Cesium3DTilesetState needed? Can we remove it and just replace it with a _rootRequested boolean in Cesium3DTileset?

It can be removed. I added it in order to support attempting to load tileset.json across multiple frames if the `RequestScheduler` was full, but that was before I added the `RequestScheduler.request` function. @pjcozzi I'm more familiar with how this should work, should I handle this one?

**Comment by pjcozzi** [comment]
@lilleyse sure, whatever you think.

**Comment by TomPed** [comment]
> UI elements for loadProgress (commented out) in Cities.html

Are these commented lined to be deleted? Or is the code to be uncommented and fixed?

**Comment by lilleyse** [comment]
We want to bring it back, and add the messages to the UI rather than just the console. Maybe it's best to skip this one for now because @pjcozzi is simplifying `3D Tiles.html` on the style branch, 

But eventually I think the idea is to have a better UI for visualizing 3D Tiles, similar to the Cesium Inspector demo. This may require looking around at other Sandcastle files for ideas.

**Comment by lilleyse** [comment]
@pjcozzi 

> Make tests like 'tile visible event is raised' verify that the event is called (check for examples in ModelSpec.js for animation events)

We have a test for `tile visible event is raised`, is this something different?

**Comment by lilleyse** [comment]
Never mind, so basically just make a spy that checks it was called.

**Comment by TomPed** [comment]
Got it.

**Comment by pjcozzi** [comment]
Potentially useful reading on V8 GC: https://medium.com/@_lrlna/garbage-collection-in-v8-an-illustrated-guide-d24a952ee3b8

**Comment by ruruiye** [comment]
what's the status for vector tiles? it's no update or example, and no spec found in 3D tile 1.0
