### ISSUE TITLE
JavaScript Code Style checker

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3309]
I've been wanting to look into the [JavaScript Code Style checker](http://jscs.info/) for a while as it is starting to become as popular as jsHint.  They also have official gulp support: https://github.com/jscs-dev/gulp-jscs, so this should be easy to integrate.

**Comment by mramato** [comment]
I took a quick look at this and had it up and running with Cesium in literally under 2 minutes using one of their default configurations and `gulp-jscs`.  The main work is going to be going through every option and figuring out what the setting for our code base should be (and then ultimately fixing anywhere we are inconsistent.

The gulp plug-in doesn't support js extractions from HTML yet (for Sandcastle checking), but their CLI does.  We can probably commit support for it back to the gulp plug-in easy enough if it still doesn't have that feature by the time we get to it.

**Comment by chris-cooper** [comment]
You may want to also consider http://editorconfig.org/

**Comment by mramato** [comment]
Thanks @chris-cooper, that's actually another thing I've wanted to check out.  In all likelihood we'll end up using both.

**Comment by pjcozzi** [comment]
Ask check out http://eslint.org/, which would replace JSHint and add style rules.  Sounds like it is widely used and has a ton of plugins.  I heard about it here: http://audio.javascriptair.com/e/010-jsair-eslint-with-feross-aboukhadijeh-gyandeep-singh-ilya-volodin-and-jamund-ferguson/

**Comment by mramato** [comment]
I know all about eslint.  I've never used it, but I've heard it has performance problems, is difficult to configure and tries to do too much.  I'm not saying it's not worth looking into, it's just the first impression I got.

I also like that jsHint is about code correctness while jscs is about code style, both have a singular goal. eslint on the other hand tries to be everything to everyone and do both.  There's actually been some [bad blood](https://github.com/eslint/eslint/issues/1774) between the jscs and eslint in the past, not that that directly affects us.

I actually did a 5 minute test of jscs and got it working in no time with like 5 line of code, since it's that easy; we might want to just turn it on sooner rather than later and then we can also revisit eslint as a replacement for both down the road.

If anyone has some actual opinions on eslint rather than my hearsay, I'd like to hear them.

**Comment by kring** [comment]
We've started using eslint because of its support for ES2015 and React JSX.  No complaints.  It finds a _ton_ of stuff and it's very configurable.

**Comment by mramato** [comment]
@kring did you just volunteer to add eslint support for us?  Because it sounds like you volunteered to add eslint support for us :)

**Comment by kring** [comment]
You guys are all Webstormy, not sure I can help you. :)  I used this guide to get it rigged up in Sublime Text:
https://medium.com/@dan_abramov/lint-like-it-s-2015-6987d44c5b48#.8h09m2v3h

We're not running it from gulp yet (no good reason, just haven't bothered as this is only in a particular branch so far) but I don't expect any difficulties.  The biggest hurdle is putting together an `.eslintrc` that doesn't flag millions of problems, or fixing the millions of problems it does flag.

**Comment by mramato** [comment]
Does eslint catch everything that jsHint can?  One major concern would be losing functionality.

Another possible gotcha for us is that we use jsHint in-browser in Sandcastle.  I suppose we could keep using jsHint when live-coding and use eslint offline.

**Comment by kring** [comment]
I assume so, it has so many rules; I have to imagine any worthwhile jshint rules have been added by now.  But I never tried to compare.

You're probably right that it's much slower.  Hopefully that's not a major concern, but if it took 20 minutes or something to run on Cesium that'd be pretty annoying.  It's probably pretty easy to do a quick test.

I can't speculate on what it would be like to run it in a browser, sorry.

**Comment by mramato** [comment]
Yeah, if it's as easy to turn on with some default rules as jscs, then we can run both and look at performance.

> I can't speculate on what it would be like to run it in a browser, sorry.

It doesn't.

**Comment by mramato** [comment]
Looks like JSCS has merged with ESLint (with ESLint being the only project moving forward).  Makes the choice easy for us.  We should evaluate ESLint soon: http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint

**Comment by pjcozzi** [comment]
Also, came across this: https://github.com/feross/standard

**Comment by mramato** [comment]
> Also, came across this: https://github.com/feross/standard

We definitely can't use/don't want this.  Hatred of JavaScript "Standard" style aside, it's a no-configuration "do it our way" tool that would dramatically change the way we write code.

**Comment by pjcozzi** [comment]
OK, not endorsing it, just making note of what I came across in my travels.

**Comment by jhwohlgemuth** [comment]
I would very much like to help integrate ESLint into this project!

From what I can tell, the path to ESLint would be something like:

- [ ] Construct `.eslintrc` file based on the rules from the current `.jshintrc` file
- [ ] Add ["eslint"](https://github.com/adametry/gulp-eslint) task to Gulpfile.js (leave the jshint task for a little while to facilitate the transition)
- [ ] Refactor jshint-related-inline-comment-creating functions in Gulpfile.js to use ESLint syntax
- [ ] Clear new lint errors/warnings and tweak rules

> might want to consider "extended" period of development with JSHint and ESLint to ease the transition...one could also set some rules as "warnings" to allow for an incremental integration into the workflow without impacting production too severely

- [ ] Remove all "hints" of JSHint (rename stuff, remove task and dep, etc...)

I made the transition from JSHint/JSCS not too long ago and have not looked back. Extendible configs (like [one I made](https://github.com/omahajs/eslint-config-omaha-prime-grade) 😉), a rich ecosystem of plugins, and the ability to make custom rules (complete with a [yeoman generator](https://github.com/eslint/generator-eslint)) make ESLint the obvious choice for any discerning ECMAScript ~~JavaScript~~ project 🎩

In any case, I would have no problem taking it step by step with updates and approvals.

**Comment by mramato** [comment]
@jhwohlgemuth that would be awesome and very much appreciated!  I think your task list sounds perfect.  The only real concern I have over eslint is possible performance issues over jshint, but I think that's just a fact we have to deal with since ultimately eslint will help us do a lot more.

I'm happy to answer any questions you have as you go.

**Comment by jhwohlgemuth** [comment]
@mramato Neat. I will endeavor to get started this weekend.

**Comment by jhwohlgemuth** [comment]
@mramato I am down to 12 lint issues that appear to be legit (or at least not intuitively obvious to a casual observer):

```bash
> npm run eslint

/cesium/Source/Core/OrientedBoundingBox.js
  184:13  error  'center' is assigned a value but never used  no-unused-vars

/cesium/Source/Scene/DebugCameraPrimitive.js
  154:25  error  'worldCoords' is assigned a value but never used  no-unused-vars

/cesium/Source/Scene/UrlTemplateImageryProvider.js
  953:13  error  'projected' is assigned a value but never used  no-unused-vars

/cesium/Source/Scene/createTileMapServiceImageryProvider.js
  109:41  error  'srs' is assigned a value but never used  no-unused-vars

/cesium/Source/DataSources/GeoJsonDataSource.js
  84:9  error  'defaultFillMaterialProperty' is assigned a value but never used  no-unused-vars

/cesium/Apps/Sandcastle/CesiumSandcastle.js
  370:14  error  A function with a name starting with an uppercase letter should only be used as a constructor  new-cap

/cesium/Apps/Sandcastle/Sandcastle-client.js
   67:38  error  Empty block statement  no-empty
  103:30  error  Empty block statement  no-empty
  148:22  error  Empty block statement  no-empty

/cesium/Specs/Core/GeometryPipelineSpec.js
  333:17  error  'geometry' is assigned a value but never used  no-unused-vars

/cesium/Specs/Scene/FrameRateMonitorSpec.js
  34:42  error  Empty block statement  no-empty

/cesium/Specs/Scene/ShadowMapSpec.js
  497:13  error  'shadowedColor' is assigned a value but never used  no-unused-vars

✖ 12 problems (12 errors, 0 warnings)

[18:42:18] Finished 'eslint' after 21 s
```
I will address these issues and ensure I do not break any tests 😉. After that, I will move on to the last step of "removing all hints of jshint" and make a PR.

**Comment by mramato** [comment]
Awesome work @jhwohlgemuth, I agree those all look like legitimate issues.  Looking forward to your pull request.

**Comment by jhwohlgemuth** [comment]
@mramato Would you like me to tackle transitioning the Sandcastle app from JSHint to ESLint in the same PR for replacing JSHint with ESLint in the Cesium source?

At this point, I am unsure of the work required to make the switch for the Sandcastle app...

> **Semi-related Question**: Have you guys ever considered handling the Sandcastle app as a separate project/repo? Feasibly, you could even share your ESLint config as a npm module (something like `eslint-config-cesium` or `eslint-config-agi`)

**Comment by mramato** [comment]
Let's handle Sandcastle separately to keep the PRs smaller and focused.

Sandcastle is an integral part of our development, so a separate project or repository is unlikely.  The only way I ever see that happening is if Sandcastle were maintained as an example application shell (with no Cesium dependency) and then Cesium just depended on it as a third party module, but honestly we have no where near the bandwidth for something like that and I'm not sure if there would really be any upside.

That being said, Sandcastle is definitely do for a large scale refactor/rewrite, but I wouldn't expect that to happen until after we switch Cesium over to ES6 models.  We've also floated the idea of breaking Cesium itself into multiple modules/packages which we ship both separately for those that need the modularity, and together as a whole (similar to our current monthly releases).  With 3D Tiles almost in master, I think some of these other large projects we want to undertake may finally see the light of day, but it's hard to put a timeframe on anything right now.

**Comment by jhwohlgemuth** [comment]
That all makes sense. Thanks for the reply.

My intention at this point is to integrate ESLint and remove all traces of JSHint (excluding the parts that are essential for Sandcastle).

I will leave the [JSHint source](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/ThirdParty/jshint-2.1.10) and probably just move the old JSHint rules into the JSHint configs used by Sandcastle ([this](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/.jshintrc) and [this](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Apps/Sandcastle/.jshintrc)) (since the root config will be replaced by and ESLint one)

**Comment by mramato** [comment]
That all makes sense, but obviously I'll have a better understanding of the big picture once the PR is open.  Feel free to open the PR sooner rather than later so people can start looking at it.  No need to wait until it's "done" done just to open the PR, just leave a comment indicating what's left to do.

**Comment by jhwohlgemuth** [comment]
@mramato Good point. And [here it is](https://github.com/AnalyticalGraphicsInc/cesium/pull/5344)

To para-phrase [Mike Tyson](https://www.brainyquote.com/quotes/quotes/m/miketyson382439.html)

> "Everyone has a plan until their PR gets punched in the face."

**Comment by pjcozzi** [comment]
OK to close this?

Does anything need a new issue?  Like:

> Replace JSHint in SandCastle App

**Comment by mramato** [comment]
I'm writing up some new issue now.  I'll close this with links.

**Comment by mramato** [comment]
Fixes in #5344 

Also see #5368, #5369, and #5370
