### ISSUE TITLE
Testing infrastructure roadmap

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3571]
#3381 added initial karma support to Cesium but left the old system in place until we are completely switched over and happy with the new one.  Here's a list of remaining tasks

**Complete migration**
- [x] Update release guide to use karma.
- [ ] Add coverage support via `istanbul`
- [x] ~~Expose `karma grep`, i.e. ability to easily run a single test or set of tests from the command line.~~ Use `fit`, `fdescribe`, or `fdefineSuite`.

**Remove old system (once the migration is done)**
- [ ] Remove test and coverage links from index.html and index.release.html
- [ ] Delete `jscoverage` since it's no longer used.
- [ ] Delete old Jasmine files and infrastructure

**CI**
- [x] Add `test-travis` target and make non-WebGL tests run as part of the CI process (in both module and minified-release form).
- [x] Publish all build output from branches to S3.
- [x] ~~Use HTML reporter in the new system (We actually use a hacked up version of https://www.npmjs.com/package/karma-jasmine-html-reporter, it might be better to use that an contribute changes back).~~ Not really needed since WebStorm integration is awesome.

**Comment by mramato** [comment]
FYI, I implemented coverage support in the `coverage` branch.  It was super trivial to do but there is currently a major performance issue that causes coverage to either fail or (with a few problematic tests excluded) take 8 minutes to run.  I'm trying to figure out what the problem is and have an email out to their forum about it: https://groups.google.com/d/msg/karma-users/te2YdIW7b7s/eyZY7A6kFgAJ

Hopefully I'll hear something back soon, otherwise I'll head over to the istanbuil repository and see if they can help me.

**Comment by mramato** [comment]
I submitted an issue to istanbul as well: https://github.com/gotwarlost/istanbul/issues/556

**Comment by pjcozzi** [comment]
OK to close this as duplicate with @omh1280's summer work?

**Comment by mramato** [comment]
Sure.
