### ISSUE TITLE
Test Cesium under node

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#3657]
Now that we ship an official Cesium node module, and the non-webgl parts are actually supposed to work under node, we should include node testing as part of the CI and release processes.  I think we can leverage all of our existing jasmine tests and run them under node unchanged (of course many will fail), and then the hard part will be to go in and make them work (where it makes sense) or add them to a "noNode" category.  In the short term, we might just be able to add a smokescreen test to ensure the module isn't every completely broken.

 - [ ] Smoke screen test for module to make sure it loads without issue.
 - [ ] Make all current non-webgl tests runnable under node via jasmine.
 - [ ] Fix any broken tests or if needed add them to the `noNode` category.

**Comment by pjcozzi** [comment]
With #4281, the "WebGL" tests will also be candidates for running under node.
