### ISSUE TITLE
BIM roadmap

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4678]
# Priority 1 - Optimizations

Optimizations for large 3D Tiles tilesets
- [ ] Texture compression
- [ ] Aanalyze latest reality model (RM) and design model (DM) tilesets
   - Do RMs have too many levels? Looking into coarser levels for DM tilesets
- [ ] Long list of optimizations in #3241 until things are smooth enough (on iPad in particular)
   - [ ] Better memory management on mobile in general
- [ ] Investigate issue with breath-first loading
- [ ] Try adding a [request volume](https://github.com/AnalyticalGraphicsInc/3d-tiles#viewer-request-volume) to a BIM model so it is not loaded until the viewer enters the volume

# Priority 2 - BIM Requirements

- [ ] **Navigation**
  - [ ] Option to keep camera "up"
  - [ ] Walk tool, including walk through walls/floors, walk at constant rate.  Constrain motion so user doesn't get lost/confused
  - [ ] "Turn off camera" - change from perspective to orthographic projection
  - [ ] Indoor mode - adjust far/near to avoid z-fighting, render environment to texture given know area of interest
- [ ] **Object selection**
  - [ ] Pick translucent objects, #4511
  - [ ] Post-processed animated silhouettes for objects of interest
  - [ ] Opaque objects of interest.  Make everything else translucent
    - @pmconne to show @pjcozzi how performance goes down likely due to extra draw calls from derived commands
- [ ] **Drawing**
  - [ ] 2D schematics in separate window. Click in a schematic to highlight/zoom in BIM view.  Also text list-view of objects, click to highlight/zoom in BIM view
    - Rasterize on server with pick IDs or send vector data to client (requires custom fonts).  @pjcozzi suggests the former

# Priority 3 - Classification of mesh + GIS data

- [ ] Polygon-on-terrain approach or texture generation at runtime, both from declarative style.  Also want to do pick and know classification
   - Branches: [3d-tiles-classification](https://github.com/AnalyticalGraphicsInc/cesium/compare/3d-tiles...3d-tiles-classification), [3d-tiles-classification-height](https://github.com/AnalyticalGraphicsInc/cesium/compare/3d-tiles...3d-tiles-classification-height)

# Priority TBA

- [ ] Not require file extensions for tiles since they are created on the fly.  Also see: https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/90#issuecomment-246207288.  Revert to https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/5 or _maybe_ only read the `magic` field if the tile format is not needed in advance
- [ ] Full lighting system when appropriate. IBL/PBR from glTF
- [ ] Enable 3D Tiles in Columbus View
- [ ] **Time-dynamic**: 4 or 5 reality models each with a time stamp.  Blending
- [ ] **Diffing/blending** BIM vs. Reality Model.  Focus on one or the other
- [ ] **Underground** - railways with signals along track
- [ ] **Site planning** - viewsheds.  When foggy, what is the visibility in a corridor?  Smoke sim, what is the path to replace a pump?

# Done

- [x] 3D Tiles declarative styling: replacement or highlight color (can we do this without using a lot of memory?)
- [x] New Batch Table design and/or Cesium tile load events so that the Batch Table can store more complex data structures with less redundancy, e.g., duplicate model IDs.  Related: https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/66
- [x] **Inside lighting**: default rig with two lights to start

**Comment by pmconne** [comment]
Regarding Navigation section:
I've ported our view navigation tools to javascript so the first 3 items in that section can probably be considered complete.
The code is rather specific to our tool/view framework but if you feel some of it could be usefully integrated into Cesium please let us know.

Regarding 'Object selection > Opaque objects of interest':
I reworked the way I manipulate the tileset style and can no longer observe significant performance degradation with transparency applied.

**Comment by pjcozzi** [comment]
> I've ported our view navigation tools to javascript so the first 3 items in that section can probably be considered complete.
> I reworked the way I manipulate the tileset style and can no longer observe significant performance degradation with transparency applied.

Very nice, updated the above roadmap.

> if you feel some of it could be usefully integrated into Cesium please let us know

Thanks for the offer.  When you have time, can you send me a demo of the walk mode?  It could be generally useful to Cesium.
