### ISSUE TITLE
Reenvision WebGL unit tests

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4817]
After #4281 ([webgl-mock-for-tests](https://github.com/AnalyticalGraphicsInc/cesium/compare/webgl-mock-for-tests#files_bucket) branch), CI will be able to run all Cesium unit tests.  Tests that require WebGL use an empty WebGL stub and skip `readPixels` and friends expectations - so all the code is ran, but not all of it is verified.

I want to move away from heavily using `readPixels` tests; those are **integration tests** with the Cesium renderer and WebGL implementation.  Some will still be included in Cesium's test suite, but most tests relying on `readPixels` can be verified reasonably well with verifying only Cesium code, e.g., with spys, validating `DrawCommands`, etc.  This will lead to a faster, easier to debug, more reliable, and more consistent test suite.  Even if it is less precise, `readPixels` expectations rarely find issues in practice and will still be with the mix TBA.

* [ ] Update WebGL stubs for WebGL 2, #797
* [ ] Consider removing `WebGL` test category
* [ ] Strategy for validating rendering code with less `readPixels`...and migration as reasonable.
* [ ] Tech blog post

**Comment by pjcozzi** [comment]
Also check out https://github.com/evanw/webgl-recorder via @austinEng
