### ISSUE TITLE
Issues to investigate at the Winter Bug Bash. Feb 8-10, 2017

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4897]
Please add a comment with your request (with links to their issues) for bug fixes and small features.

Need ideas? Review [issues labeled 'priority'](https://github.com/AnalyticalGraphicsInc/cesium/issues?q=is%3Aissue+is%3Aopen+label%3Apriority).

* [ ] Review and merge [open pull requests](https://github.com/AnalyticalGraphicsInc/cesium/pulls)
   * [ ] GPX, #2939
* [ ] Improve label quality, #2130, #2752, and #4235
* [ ] VR fixes, #4311 and #3909, @rahwang / @bagnell 
* [ ] Improve Sandcastle load time, #4906, @austinEng ?
* [x] Pick translucent objects, #4511 and #4678
* [ ] Procedural shading for 3D Tiles point clouds, @rahwang
* [ ] Update Getting Started Tutorial, http://cesiumjs.org/tutorials/cesium-up-and-running/
* [x] #4619 Polyline crashes in rotatable 2D
* [x] #4084 Scene.pickPosition support for 2D and CV
* [x] 3D Tiles i3dm in 2D, @lilleyse 
* [ ] Clustering doesn't work well in 2D and CV, #4538
* [ ] [Test failures](https://github.com/AnalyticalGraphicsInc/cesium/issues?q=is%3Aissue+is%3Aopen+label%3A%22test+failure%22), @shehzan10
* [ ] Labels/billboards/points crossing the IDL in 2D get clipped #3960
* [ ] Update obj2gltf to 2.0, #4009, @lilleyse 
* [ ] #4894 Terrain loading errror
* [ ] #4368 Pick Position problems
* [x] #4673 3d tiles unloading, @lilleyse 
* [x] Zooming scroll wheel too fast zooms through the globe to other side #4855, @likangning93 
* [ ] image quality, #3279
* [x] Fix picking for `ModelInstanceCollection`, https://groups.google.com/forum/#!msg/cesium-dev/sUcx0GLI4Qc/SlU96ZkdCQAJ, @lilleyse 
* [ ] Imagery (and terrain) maximum level is limited in certain places In CV mode #4952
* [ ] Camera stuck after limiting zoom #3984
* [x] Deprecate the ArgGisImageServerTerrainProvider? #4955
* [ ] Intermittent GlobeSurfaceTile test failures on CI #4968

See the [Winter Bug Bash](http://cesiumjs.org/2017/01/23/Winter-Bug-Bash/) blog post for more info.

**Comment by lftgly** [comment]
Patrick- How long would it take to finish and merge Andre Nunes work on GPX and or shapefile support? Less than 3 days?
THANKS for considering this:

> FYI, I'm almost done with GPX support, all the geometric features are working and just need to be made "pretty". There's some issues with time dynamic Tracks but nothing I can't fix in a couple of days. I'm improving test coverage right now and implementing some missing (non visual) features.
>
> I'd appreciate any example .gpx files you can provide for me to test this further, also feel free to fork my repository and check out the gpx branch to test it yourself. 
> 
> Patrick Cozzi, you mentioned Demos somewhere, could you please be more specific on what kind of Demos would be appreciated? Would I need to host a cesium app to showcase these Demos?
> Thanks,
> André Nunes

**Comment by emackey** [comment]
I see "VR Fixes" in your issue description.  Will there be VR headset(s) at the bug bash?

**Comment by pjcozzi** [comment]
@lftgly we'll see what kind of shape the GPX is in; I suspect it is more than three days work.  If you have time, you are welcome to evaluate it as well, or - even better - try to finish it.  Shapefiles are probably too much for this event.

@emackey we should be able to bring @bagnell's Oculus.

**Comment by krheinwald** [comment]
#4619 - Polyline crashes in rotatable 2D

**Comment by pjcozzi** [comment]
Thanks for the input, @krheinwald!  I updated the list. #4084 is especially a good call!

**Comment by jbo023** [comment]
https://github.com/AnalyticalGraphicsInc/cesium/issues/4894 Terrain loading errror
https://github.com/AnalyticalGraphicsInc/cesium/issues/4368 Pick Position problems

Also if you are working on VR Stift, i do have a HTC Vice at Home and could so some testing if necessary

**Comment by pjcozzi** [comment]
> if you are working on VR, i do have a HTC Vice at Home and could so some testing if necessary

Thanks for the offer, we'll let you know!

**Comment by jburr-nc** [comment]
We would love to see more visual improvements -- we get asked about this a lot!  The three label/text tasks are probably our most desired fixes right now. After that, possibly #3279, or anything that can improve the graphics quality without hammering performance.

**Comment by pjcozzi** [comment]
Thanks @jburr-nc!  I added #3279 to the list above, but the scope is likely to large.

**Comment by ajwinter** [comment]
We would also love to see those three visual improvement tasks taken care of. Blurry billboards (#4235) are a constant issue for us. Thanks!

**Comment by pjcozzi** [comment]
@ajwinter #4235 is on the list!

**Comment by mramato** [comment]
@jburr-nc if imagery quality is a large concern for you, I recommend disabling fxaa and setting maximumScreenSpaceError to 1.33. fxaa is make the image much more crisp (And actually improve GPU performance) and the cost of some jagginess in geometry.  Setting maximumScreenSpaceError will make Cesium request more map tiles and terrain, but will better map to what you see at zoom levels in traditional 2D maps.

```javascript
viewer.scene.fxaa = false;
viewer.scene.globe.maximumScreenSpaceError = 4/3;
```

**Comment by laurensdijkstra** [comment]
We are seeing a reduced level of Terrain detail when zoomed in and a stream of errors like `An error occurred in "CesiumTerrainProvider": Failed to obtain terrain tile X: 8449 Y: 1682 Level: 13.`

Does this have anything to do with recent updates to the way maximum detail level of Terain can be queried? Could not find an issue regarding this on Github so that's why I'm posting here directly.

**Comment by freder** [comment]
- #3984 
- picking being broken on `3d-tiles` branch

**Comment by pjcozzi** [comment]
Thanks @freder!  For picking in `3d-tiles`, what is the precise case?  Is it #4368?

**Comment by pjcozzi** [comment]
@laurensdijkstra perhaps ask on the [forum](http://cesiumjs.org/forum.html); this could be a temporary network issue.

**Comment by freder** [comment]
@pjcozzi it has to do with model instancing — [https://groups.google.com/d/msg/cesium-dev/sUcx0GLI4Qc/SlU96ZkdCQAJ](https://groups.google.com/d/msg/cesium-dev/sUcx0GLI4Qc/SlU96ZkdCQAJ)

**Comment by pjcozzi** [comment]
Gotcha, thanks!

**Comment by jhalbroo** [comment]
I'd also like to advocate for [#3279 ](https://github.com/AnalyticalGraphicsInc/cesium/issues/3279).  This has been noticed whenever I give a demo of Cesium and a different map viewer (e.g. Google, Open Layers) is shown alongside.  I reported the issue [here](https://groups.google.com/forum/?hl=en#!topic/cesium-dev/QTSlECbZmG8), which was duped to 3279.

**Comment by mramato** [comment]
@jhalbroo See https://github.com/AnalyticalGraphicsInc/cesium/issues/4897#issuecomment-277396103 above on tuning Cesium for maximum image quality.  Let me know how tweaking those settings work out for you.

The `maximumScreenSpaceError` default might be changed in the future, but we need to look at it's overall performance/memory/bandwidth impact.

I believe improvements to `fxaa` are going to require WebGL2, so they are outside the scope of the bash (though I'm not actually at the bash this time so perhaps @bagnell can chime in with more info).

**Comment by bagnell** [comment]
@jhalbroo @mramato Anti-aliasing will be improved with WebGL 2, but that is not the issue. The problem is that parts of the scene do not need to be anti-aliased (imagery, labels, ...) and others do (lines, geometry, ...). Right now, FXAA is run on the entire scene. If it is enabled, it will degrade the visual quality of parts of the scene that do not need it. If it is not, it will degrade the parts that do.

**Comment by jhalbroo** [comment]
Thanks @mramato!  I tried out the work-around and it enhanced the image quality.  I compared it to Open Layers showing the same basemap and they look comparable now.  I'll have to assess the quality when I add vector layers, but this looks promising.

**Comment by hpinkos** [comment]
@pjcozzi can we close this?

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!msg/cesium-dev/sUcx0GLI4Qc/SlU96ZkdCQAJ
https://groups.google.com/d/msg/cesium-dev/sUcx0GLI4Qc/SlU96ZkdCQAJ](https
https://groups.google.com/forum/?hl&#x3D;en#!topic/cesium-dev/QTSlECbZmG8

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/4897 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.


__I am a bot who helps you make Cesium awesome!__ Thanks again.
