### ISSUE TITLE
Post process framework roadmap

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5808]
* Initial implementation: #5615
* 5-year old [notes](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Screen-Space-Rendering-Details)
* [ ] Reuse ping-pong textures: if we're not already doing this, I realized that when we are rendering to down-sampled textures, it would probably be better to just reuse a larger texture and render to a subset of it so we overall allocate fewer textures.  Somewhat related, check out the [Transient resource system](https://www.slideshare.net/DICEStudio/framegraph-extensible-rendering-architecture-in-frostbite) in Frostbite.  Note that I expect our textures to have a lifetime of multiple frames, and eventually be deallocated like the shader cache.
* [ ] Longer-term transpiler/optimizer to combine multiple post-processing passes into one pass.  Basically we provide a set of filters/effects/passes to a pipeline/whatever object, then the pipeline object is free to optimize as it sees fit.  For more inspiration, see [Designing a next-generation post-effects pipeline](https://bartwronski.com/2014/12/09/designing-a-next-generation-post-effects-pipeline/).

**Comment by pjcozzi** [comment]
Nice article with a bit on their post processing: [Godot 3's Renderer Design Explained](https://godotengine.org/article/godot-3-renderer-design-explained)

**Comment by AdrienVR** [comment]
Hello, I can't find Tilt Shift in the list, did you forgot it ? Is it safe to use the Effects package scripts from the Unity 5.5 version when it's missing in this new version (it seems to work for me) ?

**Comment by pjcozzi** [comment]
@AdrienVR I'm not following, did you mean to comment in this issue?

**Comment by pjcozzi** [comment]
* [HDR in Floored/CBRE](https://drive.google.com/file/d/1qPU6BZCKyBwNIMywMdLDkV1VBFzwPpaW/view)

**Comment by pjcozzi** [comment]
* 50 post-processing passes (not used all at once) in [FrameGraph: Extensible Rendering Architecture in Frostbite](https://www.ea.com/frostbite/news/framegraph-extensible-rendering-architecture-in-frostbite).

**Comment by pjcozzi** [comment]
* Use large triangle instead of two triangles - up to 10% on GCN
   * [GCN Execution Patterns in Full Screen Passes](https://michaldrobot.com/2014/04/01/gcn-execution-patterns-in-full-screen-passes/)
   * [Vertex Shader Tricks: New Ways to Use the Vertex Shader to Improve Performance](http://amd-dev.wpengine.netdna-cdn.com/wordpress/media/2012/10/Vertex-Shader-Tricks-Bill-Bilodeau.ppsx)

**Comment by pjcozzi** [comment]
* Motion blur with velocity buffer in [DOOM (2016)—Graphics Study](http://www.adriancourreges.com/blog/2016/09/09/doom-2016-graphics-study/)

**Comment by pjcozzi** [comment]
* [Motion Blur Rendering: State of the Art](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.348.5981&rep=rep1&type=pdf)

**Comment by lilleyse** [comment]
Possible idea from the forum: https://groups.google.com/forum/#!topic/cesium-dev/DJiirg0L5Cs

Render translucent buildings, but have the buildings still occlude each other.

![extrude](https://user-images.githubusercontent.com/915398/34328680-bd91902c-e8b3-11e7-86fa-dae5943cea62.jpg)

It would require rendering the tileset to its own framebuffer with depth test/mask on, and then blending that framebuffer with the scene's framebuffer. It may not be hard to add this to the post processing branch as is.

**Comment by lilleyse** [comment]
Another request from the forum which should be very straightforward with post processing - change a tileset's contrast or saturation, especially useful for photogrammetry.


https://groups.google.com/forum/#!topic/cesium-dev/zQ0GEQ2SXDU

**Comment by pjcozzi** [comment]
This could also replace the current approach for contrast/saturation/etc for imagery.

**Comment by pjcozzi** [comment]
@bagnell @byumjin two questions on the current HBAO.  If we haven't done these yet, they could be good roadmap items.

* [ ] Have we looked at [Line-Sweep Ambient Obscurance](http://wili.cc/research/lsao/lsao.pdf) to reduce the number of depth buffer reads by splitting the occlusion calculation into two steps?
* [ ] Instead of using the HBAO occlusion factor, have we looked at [ground truth ambient occlusion (GTAO)](http://blog.selfshadow.com/publications/s2016-shading-course/activision/s2016_pbs_activision_occlusion.pdf)?  Is it fast and simple enough and produce notably better results for us to consider using it instead?

**Comment by pjcozzi** [comment]
* Perhaps interesting reading: [Post-processing Effects on Mobile: Optimization and Alternatives](https://community.arm.com/graphics/b/blog/posts/post-processing-effects-on-mobile-optimization-and-alternatives)

**Comment by pjcozzi** [comment]
@bagnell can you please update the tasklist at the top of this issue?

**Comment by laurensdijkstra** [comment]
Now that rendering is (at least partially) implemented, is it possible to use floating point textures in the post processing stage?

**Comment by bagnell** [comment]
@laurensdijkstra Yes. You can pass `pixelDatatype: PixelDatatype.FLOAT` as an option to `PostProcessStage`, but you must also check that `Context.floatingPointTexture` and `Context.colorBufferFloat` are supported.

**Comment by laurensdijkstra** [comment]
I have not been able to get the initial HDR rendered image of the Scene. Is it possible to obtain the HDR rendered Scene texture in a PostProcessingStage, or use that as the start of the post processing chain?

**Comment by GeorgeS2019** [comment]
@pjcozzi 

https://github.com/godotengine/godot-proposals/issues/8576

![msedge_vpO5VpX6Qt](https://github.com/CesiumGS/cesium/assets/49812372/a98f8fad-08a8-4023-9cbe-c4a49c452c10)
