### ISSUE TITLE
Cesium and Webpack

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#5816]
We're working on putting together an example app as an official recommendation on getting Cesium up and running with Webpack.

Here's the plan:

- [x] Cleanup some of the pain points we've run into in the past within the Cesium library itself. (PR #5861)
	This includes:
	 - [#5417](https://github.com/AnalyticalGraphicsInc/cesium/issues/5417)
	 - [#4876](https://github.com/AnalyticalGraphicsInc/cesium/issues/4876)
	 - Resolve issue with how Webpack compiles `require.toUrl` in `buildModuleUrl.js`

- [x] Create a new `cesium-webpack-example` repo with the reccomended `webpack.config.json` configuration. 
	* We'll be using the npm version of Cesium and compiling the `Source` directory instead of either the minified or unminified built versions of Cesium. 
	* We'll also handle managing the assets files and the built versions of the web workers
	* We'll include a `README` with how to run the repo, and any optional configurations for performance or development

- [x] Setup continuous integration test on that repo to run after every release to make sure nothing in a new release breaks the recommended Cesium setup.

Thanks, please let us know your thoughts!

**Comment by markerikson** [comment]
Yay!  Great to hear this.

I'll throw in a reminder link to my post on how to load Cesium with Webpack, and produce a DllPlugin bundle for faster builds: http://blog.isquaredsoftware.com/2017/03/declarative-earth-part-1-cesium-webpack/ .

**Comment by ggetz** [comment]
Thanks @markerikson!

**Comment by bampakoa** [comment]
@ggetz A relevant entry on the Tutorials section of the website would be great also!

**Comment by ggetz** [comment]
@bampakoa Good point, we could add something like the Webpack equivalent of the [Getting Started tutorial](https://cesiumjs.org/tutorials/cesium-up-and-running/)

**Comment by mramato** [comment]
@ggetz not sure how much this may apply to your efforts but here's a blog post about webpack performance in large project.  https://redfin.engineering/tech-talk-recap-how-to-improve-webpack-performance-in-large-projects-5435bb18dd18

**Comment by markerikson** [comment]
On which note, I've got a ton of articles on Webpack build optimization, code splitting, and other related concepts, in the [Webpack Advanced Techniques](https://github.com/markerikson/react-redux-links/blob/master/webpack-advanced-techniques.md) section of my [React/Redux links list](https://github.com/markerikson/react-redux-links).

**Comment by ggetz** [comment]
Thanks @mramato and @markerikson, I'll take a look!

**Comment by pjcozzi** [comment]
@ggetz OK to close this?  Is there anything left in the above tasklist for future work?

**Comment by ggetz** [comment]
Yep, this is good to close. #5417 and #4876 will also be resolved using the recommended config.

**Comment by mramato** [comment]
For anyone that stumbles on this issue, see @ggetz's awesome work on Cesium and webpack here: https://cesiumjs.org/tutorials/cesium-and-webpack/

**Comment by nmschulte** [comment]
@ggetz, I found that the `ThirdParty/Workers` code is not accounted for in the tutorial you've created.

Adding configuration to copy the `ThirdParty/Workers` directory via Webpack seems to resolve the issue.  My configuration looks like this now:

```
    new CopyWebpackPlugin([
        {from: path.join(paths.cesiumSource, 'Assets'), to: 'Assets'},
        {from: path.join(paths.cesiumSource, 'Widgets'), to: 'Widgets'},
        {from: path.join(paths.cesiumSource, 'ThirdParty'), to: 'ThirdParty'}
    ]), 
    new CopyWebpackPlugin([
        {from: path.join(paths.cesiumSource, '../Build/Cesium/ThirdParty/Workers'), to: 'ThirdParty/Workers'},
        {from: path.join(paths.cesiumSource, '../Build/Cesium/Workers'), to: 'Workers'}
    ])  
```

**Comment by ggetz** [comment]
Thanks @nmschulte , good catch! I've opened an issue (https://github.com/AnalyticalGraphicsInc/cesium-webpack-example/issues/4) to update this in the tutorial as well as the example repo.

**Comment by custompro12** [comment]
For anyone stumbling here from Google, the above tutorial link is no longer valid.

The documentation is available here: https://cesium.com/docs/tutorials/cesium-and-webpack/
