### ISSUE TITLE
The road to terrain on by default

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5942]
Just trying to scope all the work required to have terrain on in Cesium by default.  Feedback and missing items are encouraged!

* [ ] First ship with `depthTestAgainstTerrain` defaulted to `true`, #2160.  When that is proven to work well, a future release can enable terrain by default
* [ ] Polylines on terrain, https://github.com/AnalyticalGraphicsInc/cesium/issues/2172
* [ ] Labels/billboards partly hidden by terrain, #2694
   * [ ] Other billboard/terrain issues? https://github.com/AnalyticalGraphicsInc/cesium/issues/4686
* [ ] Points on terrain, https://github.com/AnalyticalGraphicsInc/cesium/issues/2685
* [ ] Easy and fast way to query terrain heights so that geometries, models, etc. can be automatically clamped to terrain
* [ ] Maybe cutouts to cleanly inset photogrammetry 3D tilesets (and not request the terrain tiles underneath)
* [ ] Deprecation path/guide for how to update apps to use terrain - or how to turn terrain off. Impact on loading data sources?

CC #526, #2524

**Comment by pjcozzi** [comment]
Lots of interest in terrain on by default according to our highly scientific twitter poll:

![image](https://user-images.githubusercontent.com/782098/32280909-ad3c3978-bef3-11e7-9444-4163467c130f.png)

https://twitter.com/CesiumJS/status/925361894248013824

**Comment by mramato** [comment]
After some offline conversations, and given the awesome work the community has done over the last few months, the time has come at last to enable terrain by default. The plan is to do this for Cesium Oct 1st release (1.50).  While some of the checkboxes in this issue are still valid, the scope for terrain on by default is actually fairly small so let's try to keep the discussion geared towards what is absolutely needed.

I'll re-arrange the original checklist above into what we still considered required and what is probably "nice-to-have" but please chime in with your own list if we are missing things.
