### ISSUE TITLE
Travis Integration

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#652]
There's been some talk about integrating [travis-ci](https://github.com/travis-ci/travis-ci) to partially automate merging pull requests.  Here's some ideas.
- [x] Provide a link to the build so reviewers can test and read the doc without pulling.
- [x] Run the tests.  Even if we have to run the non-WebGL tests only to start.  We can do better over time with different browsers, platforms, GPU vendors, etc.  Perhaps [js-test-driver](https://code.google.com/p/js-test-driver/) and [BrowserStack](http://www.browserstack.com/) are useful.
- [x] Publish new releases to npm
- [ ] Make the latest version of master available on the website downloads page (Not 100% sure if this is a good idea)
- [x] Warning if the build fails
- [x] Warn if doc build has warnings or errors.  The doc build might need some optimizations.  
- [x] Run JSHint

Other ideas:
- [ ] Run code coverage and warn if coveraged decreased.  Or warn if coverage for the new code is poor.
  - Or at least include a link to the build instrumented for coverage so it can be ran manually.
- [ ] Is it possible to get reliable test performance?  If so, warn if the new/modified tests significantly slowdown the tests.
- [ ] If CHANGES.md was not updated, provide a reminder to ask if it needs to be.
- [ ] If files were added/removed/modified in ThirdParty and LICENSE.md was not updated, provide a reminder to ask if it needs to be.
- [ ] If we don't have a CLA for the github user and the commits are not signed, provide a reminder about the CLA. CC #574 
- [ ] Warn if new public members do not have reference doc.

**Comment by pjcozzi** [comment]
This could be of interest, for example, to check the GitHub username against a database of users who signed the CLA: https://developer.github.com/v3/repos/statuses/

**Comment by pjcozzi** [comment]
@mramato is there any low-ish hanging fruit here that @ggetz could look at for the code sprint?

**Comment by mramato** [comment]
> Publish new releases to npm

FYI, this is just going to be an automatic part of the build process, and nothing to do with Travis.

**Comment by pjcozzi** [comment]
Related to #3571.

**Comment by pjcozzi** [comment]
@mramato OK to close this as duplicate with the ESLint, etc. work @omh1280 is doing this summer?
