### ISSUE TITLE
Image-Based Lighting

### ISSUE THREAD

**Issue by bagnell** [AnalyticalGraphicsInc/cesium#7051]
Roadmap for implementing IBL:
* [ ] Decide on format: RGBE, LogLUV, RGBM
* [ ] Decide on format container: KTX2, KTX, DDS
* [ ] Collaborate with glTF community on storage, e.g., https://github.com/KhronosGroup/glTF/pull/1377
* [x] Load diffuse and specular environment maps plus convoluted mip maps
* [x] Prototype with WebGL2 (requires textureLod in fragment shader)
* [x] Pack specular environment map and convolutions into a texture atlas using octahedral projection.
* [x] Use spherical harmonics for the diffuse irradiance map
* [x] Update default procedural IBL

**Comment by bagnell** [comment]
For RGBM and octahedral projection, see: http://webglinsights.github.io/downloads/WebGL-Insights-Chapter-16.pdf

For spherical harmonics, see: http://graphics.stanford.edu/papers/envmap/envmap.pdf

**Comment by bagnell** [comment]
For creating the environment maps: https://github.com/derkreature/IBLBaker

**Comment by OmarShehata** [comment]
This is a nice explanation of actually computing the coefficients for spherical harmonics: https://computergraphics.stackexchange.com/a/5001

And an example from Babylon of getting these coefficients from a cubemap: https://github.com/BabylonJS/Babylon.js/blob/master/src/Tools/HDR/babylon.cubemapToSphericalPolynomial.ts#L94

**Comment by TimvanScherpenzeel** [comment]
[Filament](https://github.com/google/filament) has a tool called [cmgen](https://github.com/google/filament/tree/master/tools/cmgen) that is able to create environment maps and generate the precomputed spherical harmonics. It [recently](https://github.com/google/filament/pull/319) also added the ability for octahedral projected maps. 

I've also been looking into Bash wrapping this tool in order to output all the necessary assets for IBL [here](https://github.com/timvanscherpenzeel/cubegen/tree/octagen).

**Comment by OmarShehata** [comment]
Oh, this is great @TimvanScherpenzeel ! Thanks for pointing that out. It'll be pretty useful to compare my implementation to theirs. I know I had some issues with artifacts from linear sampling and had to add a 2 pixel border to get around that, so I'm curious if they had to do the same thing. 

Additionally, this might be useful to mention in the glTF lights extension (https://github.com/KhronosGroup/glTF/pull/1377). It's still a draft, and you can see they have this note in the spherical harmonics section:

```
*(this section needs more about how the coefficients are used as well as a brief blurb about what SH are)*
*(also, we should probably just put some shader code in here for using the coefficients)*
```

So that might be a nice resource to mention there.

**Comment by OmarShehata** [comment]
Sample model we can use when implementing the glTF loading part:

https://github.com/KhronosGroup/glTF-Sample-Models/pull/201

**Comment by OmarShehata** [comment]
This was implemented in https://github.com/AnalyticalGraphicsInc/cesium/pull/7172.

The only remaining thing is using the glTF extension for defining the IBL parameters, which has an issue here: https://github.com/AnalyticalGraphicsInc/cesium/issues/7252
